name: Make
on:
  create:
    tags:
      - '*'

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Compile
        run: make -C $GITHUB_WORKSPACE
      - name: Publish
        uses: softprops/action-gh-release@v1
        with:
          files: |
            bsgemini
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: |
            jlxip/bsgemini:latest
            jlxip/bsgemini:${{ github.ref_name }}
